name: zibbly
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  intl: 0.17.0

  # firebase_core: ^1.21.0
  # firebase_core:  2.0.0
  # firebase_auth: 4.0.0
  firebase_storage: ^10.3.11
  # cloud_firestore: ^3.5.1
  # cloud_firestore: 4.0.0
  google_sign_in: 5.4.2

  loading_animation_widget: 1.2.0+4
  introduction_screen: 3.1.2
  bootstrap_icons: 1.10.2
  cached_network_image: 3.2.0
  font_awesome_flutter: 10.3.0
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.2.1
  image_picker: 0.8.3

  firebase_core_platform_interface: 4.5.1

  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  fluttertoast: ^8.1.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.5.1
    
  # firebase_core_platform_interface: ^4.5.2

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
  uses-material-design: true

